# Generated by Django 5.1.7 on 2025-03-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
