# Generated by Django 5.1.7 on 2025-03-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0005_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='San_HNT.comment'),
        ),
    ]
