# Generated by Django 5.1.7 on 2025-03-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0006_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='San_HNT/%Y/%m/'),
        ),
    ]
