# Generated by Django 5.1.7 on 2025-03-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0008_category_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='categorys',
            field=models.ManyToManyField(to='San_HNT.category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='San_HNT.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='San_HNT.customer'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='San_HNT.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='San_HNT.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='San_HNT.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='San_HNT.supplier'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='San_HNT.product'),
        ),
    ]
