# Generated by Django 5.1.7 on 2025-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0010_alter_category_description_alter_comment_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='NumberBuyed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='NumberInStore',
            field=models.IntegerField(default=1),
        ),
    ]
