# Generated by Django 5.1.7 on 2025-03-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0013_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('employee', 'Employee'), ('supplier', 'Supplier')], default='customer', max_length=10),
        ),
    ]
