# Generated by Django 5.1.7 on 2025-03-23 11:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0019_supplier_companyname_supplier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar_supplier'),
        ),
    ]
