# Generated by Django 5.1.7 on 2025-03-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0021_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CategoryID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
