# Generated by Django 5.1.7 on 2025-03-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0022_alter_category_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='avatar',
        ),
    ]
