# Generated by Django 5.1.7 on 2025-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0024_rename_supplierid_supplier_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
