# Generated by Django 5.1.7 on 2025-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0026_supplier_active_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='TotalRating',
            field=models.FloatField(default=0.0),
        ),
    ]
