# Generated by Django 5.1.7 on 2025-03-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0027_supplier_totalrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='TotalRating',
            field=models.IntegerField(default=0),
        ),
    ]
