# Generated by Django 5.1.7 on 2025-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0028_alter_supplier_totalrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='UnitPrice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='UnitPrice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='TotalRating',
            field=models.FloatField(default=0.0),
        ),
    ]
