# Generated by Django 5.1.7 on 2025-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0032_alter_product_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='UnitPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='UnitPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
