# Generated by Django 5.1.7 on 2025-03-29 06:15

import San_HNT.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0033_alter_orderdetail_unitprice_alter_product_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=San_HNT.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=San_HNT.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
