# Generated by Django 5.1.7 on 2025-03-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0037_commentimage'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='custom_users', to='auth.group'),
        ),
    ]
