# Generated by Django 5.1.7 on 2025-04-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0041_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='UnitPrice',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='UnitPrice',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=18),
        ),
    ]
