# Generated by Django 5.1.7 on 2025-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0044_alter_orderdetail_unitprice_alter_product_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
