# Generated by Django 5.1.7 on 2025-04-05 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0048_alter_order_stateorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StateOrder',
            field=models.CharField(choices=[('Chờ xác nhận', 'ChoXacNhan'), ('Đã xác nhận', 'XacNhan'), ('Chờ giao hàng', 'ChoGiaoHang'), ('Hủy', 'Huy'), ('Đã hủy', 'DaHuy'), ('Đã giao', 'DaGiao'), ('Giỏ hàng', 'GioHang')], default='ChoXacNhan', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='San_HNT.product'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
