# Generated by Django 5.1.7 on 2025-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0052_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
