# Generated by Django 5.1.7 on 2025-04-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('San_HNT', '0053_orderdetail_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='StartDate',
            field=models.DateTimeField(null=True),
        ),
    ]
